// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/"
    | "/background.js"
    | "/content-scripts/concur.js"
    | "/fonts/fonts.css"
    | "/fonts/lato-bold.ttf"
    | "/fonts/lato-regular.ttf"
    | "/fonts/oswald-500.ttf"
    | "/fonts/oswald-600.ttf"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
