/**
 * Auto-generated sidebar configuration.
 * 
 * This file is automatically generated from the docs/ folder structure.
 * To regenerate: yarn generate-sidebar
 * 
 * To modify the sidebar:
 * - Rename folders/files to change labels
 * - Reorder by renaming (alphabetical order is used)
 * - Create nested folders for hierarchical categories
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      "type": "category",
      "label": "General Practices",
      "items": [
        "general-practices/backend-endpoints",
        "general-practices/frontend-forms",
        "general-practices/frontend-hooks-and-apis",
        "general-practices/postman-api-testing",
        "general-practices/prisma-schema-shared-types",
        "general-practices/query-args-and-transformers",
        "general-practices/react-components",
        "general-practices/repository-overview"
      ]
    },
  ],
};

export default sidebars;
