FROM node:25-alpine

RUN npm install -g corepack --force && corepack enable

COPY package.json tsconfig.build.json .yarnrc.yml yarn.lock ./
COPY .yarn/releases .yarn/releases
COPY ./src/frontend/package.json ./src/frontend/tsconfig.json src/frontend/
COPY ./src/shared/package.json ./src/shared/tsconfig.json src/shared/

# Install dependencies
RUN yarn install;

COPY ./src/frontend src/frontend
COPY ./src/shared src/shared

EXPOSE 3000
CMD [ "yarn", "workspace", "frontend", "vite", "--force", "--host" ]
