services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: finishline_database
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: finishline-app
    build:
      context: ../
      dockerfile: devContainerization/Dockerfile.dev
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ../src/backend:/base/src/backend
      - ../src/frontend:/base/src/frontend
      - ../src/shared:/base/src/shared
    depends_on:
      - database
    environment:
      DATABASE_URL: 'postgresql://postgres:docker@database:5432/finishline_database'

volumes:
  pgdata:
