name: finishline-development
services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: finishline_database
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: devContainerization/Dockerfile.backend.dev
    ports:
      - '3001:3001'
    volumes:
      - ../src/backend:/base/src/backend
      - ../src/shared:/base/src/shared
    depends_on:
      - database
    env_file:
      - ../src/backend/.env
    environment:
      DATABASE_URL: 'postgresql://postgres:docker@database:5432/finishline_database'

  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: devContainerization/Dockerfile.frontend.dev
    ports:
      - '3000:3000'
    volumes:
      - ../src/frontend:/base/src/frontend
      - ../src/shared:/base/src/shared
    depends_on:
      - backend

volumes:
  pgdata:
