FROM node:20
WORKDIR /base

COPY package.json tsconfig.build.json ./
COPY ./src/backend/package.json ./src/backend/tsconfig.json src/backend/
COPY ./src/frontend/package.json ./src/frontend/tsconfig.json src/frontend/
COPY ./src/shared/package.json ./src/shared/tsconfig.json src/shared/

# Install dependencies
RUN yarn install;

COPY ./src/frontend src/frontend
COPY ./src/backend src/backend
COPY ./src/shared src/shared

# Run all build and preparation steps in a single RUN command
RUN yarn prisma:generate && yarn build:backend && yarn build:shared && yarn build:frontend:dev

EXPOSE 3001
EXPOSE 3000
CMD [ "sh", "-c", "yarn workspace backend dev & yarn workspace frontend vite --force --host" ]