name: Spike
description: For any research or investigation into a feature or our current architecture
title: '[Area] - Short Description'
labels: [spike]
body:
  - type: markdown
    attributes:
      value: For a spike ticket, please make sure to remember to add links to the resources you are pulling information from so others who are reviewing and giving feedback can also take a look at the same information you are looking at.
  - type: dropdown
    id: spike-type
    attributes:
      label: Spike Type
      description: Is this spike about the product (functional) or the implementation of the product (technical)?
      multiple: true
      options:
        - Functional
        - Technical
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What is this spike ticket looking into/trying to solve? Is this about enhancing something we currently do or looking into a new feature?
    validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: Reason for Spike
      description: Why is this spike ticket necessary?
    validations:
      required: true
  - type: textarea
    id: sidenotes
    attributes:
      label: Additional notes
      description: Add any extra comments related to the spike.
    validations:
      required: false
