const fs = require('fs');
const path = require('path');

// Paths
const DOCS_DIR = path.join(__dirname, '../docs');
const SIDEBAR_PATH = path.join(__dirname, '../sidebars.js');

/**
 * Recursively build sidebar structure from docs directory
 */
function buildSidebarStructure(dir, basePath = '') {
  const items = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  // Separate files and directories
  const files = entries.filter((e) => e.isFile() && e.name.endsWith('.md') && e.name !== 'intro.md');
  const directories = entries.filter((e) => e.isDirectory());

  // Sort alphabetically
  files.sort((a, b) => a.name.localeCompare(b.name));
  directories.sort((a, b) => a.name.localeCompare(b.name));

  // Process directories (categories)
  directories.forEach((dirEntry) => {
    const dirPath = path.join(dir, dirEntry.name);
    const categoryItems = buildSidebarStructure(dirPath, path.join(basePath, dirEntry.name));

    if (categoryItems.length > 0) {
      // Convert directory name to human-readable label
      const label = dirEntry.name
        .split('-')
        .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
        .join(' ');

      items.push({
        type: 'category',
        label: label,
        items: categoryItems
      });
    }
  });

  // Process files in current directory
  files.forEach((file) => {
    const docId = path.join(basePath, file.name.replace('.md', '')).replace(/\\/g, '/');
    items.push(docId);
  });

  return items;
}

/**
 * Generate sidebars.js file
 */
function generateSidebars() {
  try {
    console.log('🔄 Generating sidebar...\n');

    if (!fs.existsSync(DOCS_DIR)) {
      console.error(`❌ Error: Docs directory not found at ${DOCS_DIR}`);
      process.exit(1);
    }

    const sidebarItems = buildSidebarStructure(DOCS_DIR);

    const sidebarsContent = `/**
 * Auto-generated sidebar configuration.
 * 
 * This file is automatically generated from the docs/ folder structure.
 * To regenerate: yarn generate-sidebar
 * 
 * To modify the sidebar:
 * - Rename folders/files to change labels
 * - Reorder by renaming (alphabetical order is used)
 * - Create nested folders for hierarchical categories
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
${sidebarItems.map((item) => '    ' + JSON.stringify(item, null, 2).split('\n').join('\n    ')).join(',\n')},
  ],
};

export default sidebars;
`;

    fs.writeFileSync(SIDEBAR_PATH, sidebarsContent);
    console.log('✓ Generated sidebars.js\n');
  } catch (error) {
    console.error('\n❌ Error generating sidebar:');
    console.error(error.message);
    process.exit(1);
  }
}

generateSidebars();
