version: '3.8'

services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: src/frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: src/backend/Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - database