services:
  database:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  frontend:
    container_name: frontend
    build:
      context: ../
      dockerfile: src/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../src/frontend:/base/src/frontend
      - ../src/shared:/base/src/shared
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: src/backend/Dockerfile
    volumes:
      - ../src/backend:/base/src/backend
      - ../src/shared:/base/src/shared
    ports:
      - "3001:3001"
    depends_on:
      - database

volumes:
  pgdata: