name: Send Hourly Slack Notifications

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  send_event_notifications:
    runs-on: ubuntu-latest
    environment: notifications
    steps:
      - name: Send hourly notifications
        run: |
          curl --fail-with-body -H "Authorization: ${{ secrets.NOTIFICATION_ENDPOINT_SECRET }}" -X POST "${{ secrets.BACKEND_URL }}/notifications/hourly"