name: Send Slack Notifications

on:
  schedule:
    - cron: '0 14 * * *'

jobs:
  send_notifications:
    runs-on: ubuntu-latest
    environment: notifications
    steps:
      - name: Send notifications
        run: |
          curl -H "Authorization: ${{ secrets.NOTIFICATION_ENDPOINT_SECRET }}" -X POST "${{ env.BACKEND_URL}}/notifications/task-deadlines"
