name: Send Task Deadline Notifications

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  send_notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send notifications
        run: |
          curl -X GET https://api.finishlinebyner.com/tasks/sendTaskDeadlineSlackNotifications \
          -H 'Authorization: ${{ secrets.NOTIFICATION_ENDPOINT_SECRET }}'
