name: Send Task Deadline Notifications

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  send_notifications:
    runs-on: ubuntu-latest
    environment: notifications
    steps:
      - name: Send notifications
        run: |
          curl -H "Authorization: ${{ secrets.NOTIFICATION_ENDPOINT_SECRET }}" -X POST "https://api.finishlinebyner.com/notifications/task-deadlines"
